spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
  application:
    name: movie-fun-app

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: <access key id>
  secretKey: <secret access key>
  bucketName: <name of the bucket>

albums:
  url: "http://album-service/albums"
movies:
  url: "http://movie-service/movies"
